//
//  VaccineCountry.swift
//  VaccineInfoWidgetExtension
//
//  Created by Neil Jain on 2/21/21.
//

import Foundation

enum VaccineCountry: Int {
    case Albania = 1
    case Algeria
    case Andorra
    case Anguilla
    case Argentina
    case Austria
    case Azerbaijan
    case Bahrain
    case Bangladesh
    case Barbados
    case Belgium
    case Bermuda
    case Bolivia
    case Brazil
    case Bulgaria
    case Cambodia
    case Canada
    case CaymanIslands
    case Chile
    case China
    case Colombia
    case CostaRica
    case Croatia
    case Cyprus
    case Czechia
    case Denmark
    case DominicanRepublic
    case Ecuador
    case Egypt
    case England
    case Estonia
    case FaeroeIslands
    case Finland
    case France
    case Germany
    case Gibraltar
    case Greece
    case Greenland
    case Guernsey
    case Guinea
    case Guyana
    case Hungary
    case Iceland
    case India
    case Indonesia
    case Iran
    case Ireland
    case IsleofMan
    case Israel
    case Italy
    case Japan
    case Jersey
    case Kuwait
    case Latvia
    case Liechtenstein
    case Lithuania
    case Luxembourg
    case Macao
    case Maldives
    case Malta
    case Mauritius
    case Mexico
    case Monaco
    case Morocco
    case Myanmar
    case Nepal
    case Netherlands
    case NorthernCyprus
    case NorthernIreland
    case Norway
    case Oman
    case Pakistan
    case Palau
    case Panama
    case Peru
    case Poland
    case Portugal
    case Qatar
    case Romania
    case Russia
    case SaintHelena
    case SaudiArabia
    case Scotland
    case Serbia
    case Seychelles
    case Singapore
    case Slovakia
    case Slovenia
    case SouthAfrica
    case Spain
    case SriLanka
    case Sweden
    case Switzerland
    case Turkey
    case TurksAndCaicosIslands
    case UnitedArabEmirates
    case UnitedKingdom
    case UnitedStates
    case Wales
}

extension VaccineCountry {
    var searchKey: String {
        switch self {
        case .Albania:
            return "Albania"
        case .Algeria:
            return "Algeria"
        case .Andorra:
            return "Andorra"
        case .Anguilla:
            return "Anguilla"
        case .Argentina:
            return "Argentina"
        case .Austria:
            return "Austria"
        case .Azerbaijan:
            return "Azerbaijan"
        case .Bahrain:
            return "Bahrain"
        case .Bangladesh:
            return "Bangladesh"
        case .Barbados:
            return "Barbados"
        case .Belgium:
            return "Belgium"
        case .Bermuda:
            return "Bermuda"
        case .Bolivia:
            return "Bolivia"
        case .Brazil:
            return "Brazil"
        case .Bulgaria:
            return "Bulgaria"
        case .Cambodia:
            return "Cambodia"
        case .Canada:
            return "Canada"
        case .CaymanIslands:
        return "Cayman%20Islands"
        case .Chile:
            return "Chile"
        case .China:
            return "China"
        case .Colombia:
            return "Colombia"
        case .CostaRica:
        return "Costa%20Rica"
        case .Croatia:
            return "Croatia"
        case .Cyprus:
            return "Cyprus"
        case .Czechia:
            return "Czechia"
        case .Denmark:
            return "Denmark"
        case .DominicanRepublic:
        return "Dominican%20Republic"
        case .Ecuador:
            return "Ecuador"
        case .Egypt:
            return "Egypt"
        case .England:
            return "England"
        case .Estonia:
            return "Estonia"
        case .FaeroeIslands:
        return "Faeroe%20Islands"
        case .Finland:
            return "Finland"
        case .France:
            return "France"
        case .Germany:
            return "Germany"
        case .Gibraltar:
            return "Gibraltar"
        case .Greece:
            return "Greece"
        case .Greenland:
            return "Greenland"
        case .Guernsey:
            return "Guernsey"
        case .Guinea:
            return "Guinea"
        case .Guyana:
            return "Guyana"
        case .Hungary:
            return "Hungary"
        case .Iceland:
            return "Iceland"
        case .India:
            return "India"
        case .Indonesia:
            return "Indonesia"
        case .Iran:
            return "Iran"
        case .Ireland:
            return "Ireland"
        case .IsleofMan:
        return "Isle%20of%20Man"
        case .Israel:
            return "Israel"
        case .Italy:
            return "Italy"
        case .Japan:
            return "Japan"
        case .Jersey:
            return "Jersey"
        case .Kuwait:
            return "Kuwait"
        case .Latvia:
            return "Latvia"
        case .Liechtenstein:
            return "Liechtenstein"
        case .Lithuania:
            return "Lithuania"
        case .Luxembourg:
            return "Luxembourg"
        case .Macao:
            return "Macao"
        case .Maldives:
            return "Maldives"
        case .Malta:
            return "Malta"
        case .Mauritius:
            return "Mauritius"
        case .Mexico:
            return "Mexico"
        case .Monaco:
            return "Monaco"
        case .Morocco:
            return "Morocco"
        case .Myanmar:
            return "Myanmar"
        case .Nepal:
            return "Nepal"
        case .Netherlands:
            return "Netherlands"
        case .NorthernCyprus:
        return "Northern%20Cyprus"
        case .NorthernIreland:
        return "Northern%20Ireland"
        case .Norway:
            return "Norway"
        case .Oman:
            return "Oman"
        case .Pakistan:
            return "Pakistan"
        case .Palau:
            return "Palau"
        case .Panama:
            return "Panama"
        case .Peru:
            return "Peru"
        case .Poland:
            return "Poland"
        case .Portugal:
            return "Portugal"
        case .Qatar:
            return "Qatar"
        case .Romania:
            return "Romania"
        case .Russia:
            return "Russia"
        case .SaintHelena:
        return "Saint%20Helena"
        case .SaudiArabia:
        return "Saudi%20Arabia"
        case .Scotland:
            return "Scotland"
        case .Serbia:
            return "Serbia"
        case .Seychelles:
            return "Seychelles"
        case .Singapore:
            return "Singapore"
        case .Slovakia:
            return "Slovakia"
        case .Slovenia:
            return "Slovenia"
        case .SouthAfrica:
        return "South%20Africa"
        case .Spain:
            return "Spain"
        case .SriLanka:
        return "Sri%20Lanka"
        case .Sweden:
            return "Sweden"
        case .Switzerland:
            return "Switzerland"
        case .Turkey:
            return "Turkey"
        case .TurksAndCaicosIslands:
        return "Turks%20and%20Caicos%20Islands"
        case .UnitedArabEmirates:
            return "United%20Arab%20Emirates"
        case .UnitedKingdom:
            return "United%20Kingdom"
        case .UnitedStates:
            return "United%20States"
        case .Wales:
            return "Wales"
        }
    }
}
